### ISSUE TITLE
Checking for separator fails for keys that happen to be integers (non-iterable)

### ISSUE THREAD

**Issue by bartbroere** [HolmesNL/confidence#41]
Given a yaml where a key is an integer, ``confidence`` crashes on trying to find the separator in this key.

Example configuration yaml:
```yaml
datasets:
  2013: 'data_for_2013.xlsx'
```

Bottom of stacktrace:
```
if separator in key:
TypeError: argument of type 'int' is not iterable
```

As a user, I can easily correct this by simply making the integer a string in my configuration file. Maybe ``confidence`` could skip searching separators in non-iterable keys.

**Comment by akaIDIOT** [comment]
Fixed merging #45.
