### ISSUE TITLE
Configuration attributes of list type do not act as lists

### ISSUE THREAD

**Issue by zyronix** [HolmesNL/confidence#59]
Example code:
```
import confidence

config = {
            'parameter': ['item1', 'item2'],


        }

config_obj = confidence.Configuration(config)

list2 = ['item3', 'item4']

print(config_obj.get('parameter') + list2)
```

Returns:
TypeError: unsupported operand type(s) for +: 'Configuration' and 'list'

Expected:
['item1', 'item2', 'item3', 'item4']

Workaround:
```
print([x for x in config_obj.get('parameter')] + list2)
```

It seems the whole behavior has changed regarding to lists.

Because this used to work as well:

```
print(config_obj.get('parameter').extend(list2))
```

**Comment by akaIDIOT** [comment]
Ah yes, 0.7 wrapped sequences to be able to keep `dict`s in `list`s working as other `dict`s, think we failed to account for `list` methods that don't come with `Sequence`... 

Operators like + should be doable, they'll always return a new `list`. Whether that should be a `list` or a wrapper is tricky, would `dict`s plussed to a wrapped sequence be considered `Configuration` objects or should that operation 'plain down' the result?

Calls like `extend` or `append` (things that change a `list`) won't work I'd think; we've disabled write operations before as that was causing very awkward issues...

`list(config.get('parameter') + list2` might be even easier than the comprehension workaround btw :)

**Comment by akaIDIOT** [comment]
@zyronix would you care to take a look at #61? Are there other operations you'd expect to be supported? Things like `extend` won't work for the foreseeable future, changes in the underlying data have been hard to get right...

**Comment by zyronix** [comment]
@akaIDIOT Sorry for late response, but tested it with my example and in my code. Issue is resolved with this pull request. Thanks!
Extend was just an example to solve it, I mainly need the add operation, I dont need other operations for now.
